apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: wils
spec:
  containers:
    - image: google/cloud-sdk:slim
      name: test
      command: ["sleep","infinity"]
  serviceAccountName: wils
